plugins {
	id 'net.fabricmc.fabric-loom' version '1.17.12'
	id 'maven-publish'
	id "me.modmuss50.mod-publish-plugin" version "2.1.1"
}

publishMods {
    changelog = providers.fileContents(layout.projectDirectory.file("CHANGELOG.md")).asText
    type = STABLE
	file = jar.archiveFile
    modLoaders.add("fabric")

//	minecraftVersionRange {
//            start = "1.19.4"
//            end = "1.20.2" // Set to "latest" or "latestRelease" to use the latest Minecraft release
//
//        }

	 modrinth {
		accessToken = providers.environmentVariable("MODRINTH_API_KEY")
		projectDescription = providers.fileContents(layout.projectDirectory.file("README.md")).asText
		projectId = "wmVGLWK1"
		environment = CLIENT_ONLY
		displayName = "${mod_version}"
		version = "${mod_version}"
		 minecraftVersionList("${minecraft_version}")
	}

//	curseforge {
//		accessToken = providers.environmentVariable("CF_API_KEY")
//		minecraftVersionList("${minecraft_version}")
//		projectId = "1615155"
//		javaVersions.add(JavaVersion.VERSION_25)
//		client = true
//		changelogType = "markdown"
//
//	}

	github {
        accessToken = providers.environmentVariable("GITHUB_TOKEN")
        repository = "TechPro424/Disable-Hotbar-Scrolling"
        commitish = "master" // This is the branch the release tag will be created from
		tagName = "v${mod_version}"
		displayName = "v${mod_version}"
    }

}

base {
	archivesName = project.archives_base_name
}

version = project.mod_version
group = project.maven_group

repositories {
	// Add repositories to retrieve artifacts from in here.
	// You should only use this when depending on other mods because
	// Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
	// See https://docs.gradle.org/current/userguide/declaring_repositories.html
	// for more information about repositories.
	exclusiveContent {
		// Other repositories can go above or below Modrinth's. It does not need priority :)
    	// Note: this is NOT the `repositories` block in `pluginManagement`! This is its own block.
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
	}
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	//modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

	// Uncomment the following line to enable the deprecated Fabric API modules. 
	// These are included in the Fabric API production distribution and allow you to update your mod to the latest modules at a later more convenient time.

	// modImplementation "net.fabricmc.fabric-api:fabric-api-deprecated:${project.fabric_version}"
	api include("maven.modrinth:mixintrace:1.1.1+1.17")
}

processResources {
//	def version = project.version
//	inputs.property "version", project.version

	//	filesMatching("fabric.mod.json") {
//		expand "version": version
//  }

	var properties = [
			"version"           : version,
			"loader_version"    : loader_version,
			"fabric_api_version": fabric_api_version,
			"minecraft_version" : minecraft_version
	]

	inputs.properties properties
	filesMatching("fabric.mod.json") {
		filteringCharset = "UTF-8"
		expand properties
	}
}

tasks.withType(JavaCompile).configureEach {
	// Minecraft 1.18 (1.18-pre2) upwards uses Java 17.
	it.options.release = 25
}

java {
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()
}

jar {
	inputs.property "archivesName", base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}"}
	}
}

// configure the maven publication
publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}
